### ISSUE TITLE
8Ball

### ISSUE THREAD

**Issue by Observation-zz** [gempir/gempbot-node#3]
New command !8ball or something fitting. Use !8ball <Question for 8ball>. Command will pull a random quote from a random viewers logs as a respond for the question asked. Example, -Billy123: Will Forsen ever be lucky? -Gempbot: "Random quote" or -Gempbot: "-Billy123: Will Forsen ever be lucky?" <Can add something dank for the roleplayers here> "Random quote"

**Comment by gempir** [comment]
done
